# Generated by Django 4.0.5 on 2022-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_measure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measure_temp',
            field=models.FloatField(),
        ),
    ]
